apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  selector:
    matchLabels:
      app: petclinic
  replicas: 1 
  template: 
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: kankaranagendrareddy/petclinic:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
spec:
  type: NodePort
  selector:
    app: petclinic
  ports:
    - port: 80
      nodePort: 30007

